routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'ParserController@index')->middleware('auth');

Route::post('/', 'ParserController@add');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/categories/products/{id}', 'ProductController@show')->name('categories.product');
Route::get('/categories/products/{id}/edit', 'ProductController@edit')->name('categories.editor');
Route::resource('categories', 'CategoryController')
    ->names('categories')->middleware('auth');

Route::resource('products', 'ProductController')
    ->names('products')->middleware('auth');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Category
 *
 * @package App\Models
 *
 * @property string                    $c_id
 * @property string                    $c_name
 */
class Category extends Model
{
    protected $primaryKey = 'c_id';
    public $timestamps = false;
    public $incrementing = false;

    protected $fillable
        = [
            'c_id',
            'c_name',
        ];


    /**
     * Category & Product relations.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function product()
    {
        return $this->belongsToMany(Product::class, 'product_categories', 'category_id', 'product_id');
    }

    /**
     * Saving category into DB.
     * @param $inputCategory
     */
    public function saveCategories($inputCategory)
    {
        foreach ($inputCategory as $category => $categoryId) {
            $cat = new Category();
            $cat->c_id = $categoryId;
            $cat->c_name = $category;
            $cat->save();
        }
    }

    /**
     * Get category from DB.
     * @param $id
     * @param $number
     * @return mixed
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function getCategory($id)
    {
        $result = Category::find($id)->product();

        return $result;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Models\Category;


class CategoryController extends Controller
{
    /**
     * Show all categories.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $item = new Category();

        $paginator = $item->paginate(5);

        return view('categories.index')
            ->with(compact('paginator'));
    }


    /**
     * Show products, which are related to category.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = new Category();

        $getCategory = $item->getCategory($id)->paginate(5);

        return view('categories.show')
            ->with(compact('getCategory'));

    }

    public function edit($id)
    {
        $item = new Product();

        $product = $item->getProduct($id);

        $image = $item->getImage($id);

        return view('categories.edit')
            ->with(compact('product'))
            ->with(compact('image'));
    }

    /**
     * Updating product.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item = new Product();

        $productUpd = $item->updateProduct(
            $id,
            $request->p_name,
            $request->description,
            $request->specification,
            $request->price
        );

        if ($productUpd){
            return redirect()
                ->route('categories.edit', $id)
                ->with(['success' => 'Збережено успішно!']);
        } else {
            return back()
                ->withErrors(['msg' => "Помилка збереження!"])
                ->withInput();
        }
    }

    /**
     * Deleting product.
     *
     * @param  int  $id
     * @return \App\Models\Product $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Product $product)
    {
        $result = $product->productDelete($id);

        if ($result){
            return redirect()
                ->route('categories.index')
                ->with(['success' => "Товар з ідентифікатором [$id] був видалений!"]);
        } else {
            return back()
                ->withErrors(['msg' => "Помилка видалення!"])
                ->withInput();
        }
    }
}

resources/views/categories/includes/item_edit_add_col.blade.php
@php
    /** @var \App\Models\Product $item */
@endphp
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form method="POST" action="{{ route('products.update', $product->p_id) }}">
                    @method('PATCH')
                    @csrf
                    <button type="submit" class="btn btn-success">Зберегти</button>
                </form>
            </div>
        </div>
    </div>
</div>
<br>

<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <form method="POST" action="{{ route('products.destroy', $product->p_id) }}">
                    @method('DELETE')
                    @csrf
                    <button type="submit" class="btn btn-danger">Видалити</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/categories/includes/item_edit_main_col.blade.php
@php
    /** @var \App\Models\Product $item */
@endphp
<div class="row justify-content-center">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title"></div>
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="tab" href="#maindata" role="tab">Основна інформація</a>
                    </li>
                </ul>
                <br>
                <div class="tab-content">
                    <div class="tab-pane active" id="maindata" role="tabpanel">
                        <div class="form-group">
                            <label for="p_name">Назва :</label>
                            <input name="p_name" value="{{ $product->p_name }}"
                                   id="p_name"
                                   type="text"
                                   class="form-control"
                                   minlength="3"
                                   required>

                        </div>

                        <div class="form-group">
                            <label for="description">Опис :</label>
                            <textarea name="description"
                                      id="description"
                                      class="form-control"
                                      rows="3">{{ old('description', strip_tags($product->description)) }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="specification">Специфікація :</label>
                            <textarea name="specification"
                                      id="specification"
                                      class="form-control"
                                      rows="3">{{ old('description', strip_tags($product->specification)) }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="slug">Ціна :</label>
                            <input name="price" value="{{ $product->price }}"
                                   id="price"
                                   type="number"
                                   class="form-control">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/categories/includes/result_messages.blade.php
@if($errors->any())
    <div class="row justify-content-center">
        <div class="col-md mx-auto">
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
                {{ $errors->first() }}
            </div>
        </div>
    </div>
@endif

@if(session('success'))
    <div class="row justify-content-center">
        <div class="col-md mx-auto">
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true"></span>
                </button>
                {{ session()->get('success') }}
            </div>
        </div>
    </div>
@endif